### PR TITLE
Test for switching of Light/Dark Themes

### PR DESCRIPTION
**Pull request by perdrix52**
Switch Light/Dark Themes - will have to find a home for the buttons! Please try it anyhow

### CODE REVIEW

**Comment by pkane2001** [comment]
I like it!

**Comment by perdrix52** [comment]
Yes, but somethings awry with the persistence as no cookie is being save AFAICT L

**Comment by pkane2001** [comment]
It remembers the last setting for me. Are you sure no cookie is set?

**Comment by perdrix52** [comment]
Difference I think is you’re testing on gemini-2.net while I’m testing on localhost. probably the .js code is detecting that and not playing …

**Comment by pkane2001** [comment]
That makes sense.

Just merged the updated latitude/longitude/UTC offset calculation page. Changed it to use Bing geocoding from Google, which is now pay-only. Bing is still free.

**Pull request merged**
